### ISSUE TITLE
Design a new collective report template Daxing District (language: Chinese)

### ISSUE THREAD

**Issue by psychelzh** [iquizoo/reports#3]
Two versions of reports are required:

- [x] Report for each school. #4 
- [x] Report for the whole district. #11

**Comment by psychelzh** [comment]
[This PDF document](https://github.com/iquizoo/reports/files/2052087/M.X.Y.-.S.pdf) is a sample. And after reading it, here are the most important ideas:

1. There need to be two main parts: gross and details.
1. Descriptive statistics are sufficient.

**Comment by psychelzh** [comment]
Here comes the final stage. The reports need to be veried.

**Comment by Harrityin** [comment]
我再检查一遍
